//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProductMappings = new HashSet<OrderProductMapping>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public double Amount { get; set; }
        public int OrderStatusId { get; set; }
        public int PaymentTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Status { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductMapping> OrderProductMappings { get; set; }
    }
}
